/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package parqueamiento;

import BD_Cliente.EliminarCliente;
import BD_Cliente.ListarCliente;
import BD_Cliente.ModificarCliente;
import BD_Cliente.addCliente;
import BD_Usuario.addUsuario;
import BD_Configuracion.modConfiguracion;

import BD_Esspacio.Liberar_espacio;
import BD_Esspacio.Modificar_Espacio;
import BD_Esspacio.addEspacio;


import BD_Usuario.ModificarPassword;
import BD_Usuario.ModificarUsuario;
import BD_Usuario.addUsuario;
import Control_BD.Control_Consultas;
import Control_BD.vaciar_base_de_datos;

import about.About;

import consultas.ConsultarFacturas;


import consultas.MenuConsultas;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author tusolutionweb tutos
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
                    String master = System.getProperty("user.dir") + "/src/Icon/main.png";
//            String master = System.getProperty("user.dir") + "/Reportes/reporteproductos.jasper";
            System.out.println("master" + master);
        this.setContentPane(new JLabel(new ImageIcon(master)));//añade una 
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_archivo = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu_base_de_datos = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu_mesas = new javax.swing.JMenu();
        jMenuItem_agregar_mesas = new javax.swing.JMenuItem();
        jMenuItem_mod_mesas = new javax.swing.JMenuItem();
        jMenuItem_liberar_mesas = new javax.swing.JMenuItem();
        jMenu_acerca = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem_config = new javax.swing.JMenuItem();
        jMenu_ventas = new javax.swing.JMenu();
        jMenu_consultas_ventas = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu_vaciar_bd = new javax.swing.JMenu();
        jMenu_caja = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/document-preview (1).png"))); // NOI18N
        jButton1.setText("Consultas");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, 70));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_to_basket (1).png"))); // NOI18N
        jButton2.setText("Ventas");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, 70));

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenu_archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Archivo.png"))); // NOI18N
        jMenu_archivo.setText("Archivo");

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout (2).png"))); // NOI18N
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu_archivo.add(jMenuItem5);

        jMenuBar1.add(jMenu_archivo);

        jMenu_base_de_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/database-storage (1).png"))); // NOI18N
        jMenu_base_de_datos.setText("Base de Datos");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Person_Undefined_Male_Light_1.png"))); // NOI18N
        jMenu4.setText("Clientes");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/contact-new.png"))); // NOI18N
        jMenuItem12.setText("Agregar nuevo Cliente");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user-info.png"))); // NOI18N
        jMenuItem4.setText("Modificar Cliente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Folder Black User.png"))); // NOI18N
        jMenuItem7.setText("Consultar Clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenu_base_de_datos.add(jMenu4);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/trabajadores.png"))); // NOI18N
        jMenu8.setText("Usuarios");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/order-192.png"))); // NOI18N
        jMenuItem1.setText("Agregar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user-info.png"))); // NOI18N
        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/lock.png"))); // NOI18N
        jMenuItem3.setText("Cambiar password");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenu_base_de_datos.add(jMenu8);

        jMenu_mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/aparcamiento.png"))); // NOI18N
        jMenu_mesas.setText("Espacio");

        jMenuItem_agregar_mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/contact-new.png"))); // NOI18N
        jMenuItem_agregar_mesas.setText("Agregar");
        jMenuItem_agregar_mesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_agregar_mesasActionPerformed(evt);
            }
        });
        jMenu_mesas.add(jMenuItem_agregar_mesas);

        jMenuItem_mod_mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/modif.png"))); // NOI18N
        jMenuItem_mod_mesas.setText("Modificar");
        jMenuItem_mod_mesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_mod_mesasActionPerformed(evt);
            }
        });
        jMenu_mesas.add(jMenuItem_mod_mesas);

        jMenuItem_liberar_mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/modif.png"))); // NOI18N
        jMenuItem_liberar_mesas.setText("Liberar espacio");
        jMenuItem_liberar_mesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_liberar_mesasActionPerformed(evt);
            }
        });
        jMenu_mesas.add(jMenuItem_liberar_mesas);

        jMenu_base_de_datos.add(jMenu_mesas);

        jMenuBar1.add(jMenu_base_de_datos);

        jMenu_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Herramientas.png"))); // NOI18N
        jMenu_acerca.setText("Mas.");

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User.png"))); // NOI18N
        jMenuItem14.setText("Acerca de Programas");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu_acerca.add(jMenuItem14);

        jMenuItem_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Herramientas.png"))); // NOI18N
        jMenuItem_config.setText("Configuracion");
        jMenuItem_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_configActionPerformed(evt);
            }
        });
        jMenu_acerca.add(jMenuItem_config);

        jMenuBar1.add(jMenu_acerca);

        jMenu_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/aparcamiento.png"))); // NOI18N
        jMenu_ventas.setText("Ventas(POS) ");
        jMenu_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ventasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_ventas);

        jMenu_consultas_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/document-preview (1).png"))); // NOI18N
        jMenu_consultas_ventas.setText("Consultas Ventas");
        jMenu_consultas_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_consultas_ventasMouseClicked(evt);
            }
        });

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/buscar.png"))); // NOI18N
        jMenuItem9.setText("Ventas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu_consultas_ventas.add(jMenuItem9);

        jMenuBar1.add(jMenu_consultas_ventas);

        jMenu_vaciar_bd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/database-storage (1).png"))); // NOI18N
        jMenu_vaciar_bd.setText("Vaciar base de datos");
        jMenu_vaciar_bd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_vaciar_bdMouseClicked(evt);
            }
        });
        jMenu_vaciar_bd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu_vaciar_bdKeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu_vaciar_bd);
        jMenu_vaciar_bd.getAccessibleContext().setAccessibleName("");

        jMenu_caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/pagos.png"))); // NOI18N
        jMenu_caja.setText("caja");

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/order-192.png"))); // NOI18N
        jMenuItem17.setText("Lista Cajas");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu_caja.add(jMenuItem17);

        jMenuBar1.add(jMenu_caja);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void backup(){
 try {
            /* - Datos de acceso a nuestra base de datos */
            /* Usa localhost si el servidor corre en la misma maquina, de lo 
            contrario utiliza la IP o dirección del sevidor*/
            String dbServer = "localhost";
            /* El usuario de tu base de datos*/
            String dbName = "sysultimate_2022";
            /* El usuario de tu base de datos*/
            String dbUser = "root";
            /* La contraseña de la base de datos (dejarla en texto plano puede 
            ser un problema)*/
            String dbPass = "";
            
            /*El nombre o ruta a donde se guardara el archivo de volcado .sql*/
            String sqlFile = "backups\respaldo.sql";
 
            /* La linea de comando completa que ejecutara el programa*/
            String command = "bin/mysqldump --host " + dbServer + " -u " + dbUser
                    + " -p" + dbPass + " " + dbName + " -r " + sqlFile;
 
            /*Se crea un proceso que ejecuta el comando dado*/
            Process bck = Runtime.getRuntime().exec(command);
            
            /* Obtiene el flujo de datos del proceso, esto se hace para obtener 
            el texto del proceso*/
            InputStream stdout = bck.getErrorStream();
            
            /* Se obtiene el resultado de finalizacion del proceso*/
            int resultado = bck.waitFor();
            
            String line;
 
            /* Se crea un buffer de lectura con el flujo de datos outstd y ese mismo
            sera leido e impreso, esto mostrara el texto que muestre el programa
            mysqldump, de esta forma sabra cual es el error en su comando*/
            BufferedReader brCleanUp
                    = new BufferedReader(new InputStreamReader(stdout));
            while ((line = brCleanUp.readLine()) != null) {
                System.out.println(line);
            }
            brCleanUp.close();
 
            if (resultado == 0) {
                System.out.println("Respaldo exitoso");
            } else {
                System.out.println("Error al respaldar");
            }
        } catch (IOException | InterruptedException ex) {
            System.out.println("Exception: " + ex.getMessage());
        }
    }

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new ModificarCliente(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new addCliente(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Ventas.main(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new ListarCliente(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenuConsultas(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setForeground(Color.ORANGE);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setForeground(Color.black);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setForeground(Color.ORANGE);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton1MouseExited

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        //About.main(null);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenu_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ventasMouseClicked
        // TODO add your handling code here:
        Control_Consultas cons=new Control_Consultas();
       int contador= cons.buscarestadocaja();
       if(contador==0){
           Abrircaja.main(null);
       }
        if(contador==1){
        Ventas.main(null);
            } 
          
    }//GEN-LAST:event_jMenu_ventasMouseClicked

    private void jMenu_consultas_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_consultas_ventasMouseClicked
        // TODO add your handling code here:
//             new MenuConsultas(this, true).setVisible(true);
    }//GEN-LAST:event_jMenu_consultas_ventasMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
           new addUsuario(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_configActionPerformed
        // TODO add your handling code here:
     new modConfiguracion(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem_configActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
             new ModificarUsuario(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          new ModificarPassword(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu_vaciar_bdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu_vaciar_bdKeyPressed
        // TODO add your handling code here:
       backup();
    }//GEN-LAST:event_jMenu_vaciar_bdKeyPressed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
          //     Ventas.main(null);
          
//              ConsultarFacturas.main(null);
                       new ConsultarFacturas(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
               new Lista_cajas(this, true).setVisible(true);

    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenu_vaciar_bdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_vaciar_bdMouseClicked
        // TODO add your handling code here:
        vaciar_base_de_datos v= new vaciar_base_de_datos();
        v.Eliminar_db();
    }//GEN-LAST:event_jMenu_vaciar_bdMouseClicked

    private void jMenuItem_agregar_mesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_agregar_mesasActionPerformed
        // TODO add your handling code here:
        
             new addEspacio(this, true).setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_agregar_mesasActionPerformed

    private void jMenuItem_mod_mesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_mod_mesasActionPerformed
        // TODO add your handling code here:
              new Modificar_Espacio(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem_mod_mesasActionPerformed

    private void jMenuItem_liberar_mesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_liberar_mesasActionPerformed
        // TODO add your handling code here:
             new Liberar_espacio(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem_liberar_mesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_agregar_mesas;
    private javax.swing.JMenuItem jMenuItem_config;
    private javax.swing.JMenuItem jMenuItem_liberar_mesas;
    private javax.swing.JMenuItem jMenuItem_mod_mesas;
    public static javax.swing.JMenu jMenu_acerca;
    public static javax.swing.JMenu jMenu_archivo;
    public static javax.swing.JMenu jMenu_base_de_datos;
    public static javax.swing.JMenu jMenu_caja;
    public static javax.swing.JMenu jMenu_consultas_ventas;
    private javax.swing.JMenu jMenu_mesas;
    public static javax.swing.JMenu jMenu_vaciar_bd;
    public static javax.swing.JMenu jMenu_ventas;
    // End of variables declaration//GEN-END:variables
}
