if(!window.fjit){window.fjit={isNewVisit:false,wUrlMap:{trafficList:"http://feedjit.com/serve",map:"http://feedjit.com/map",popPages:"http://feedjit.com/popPages",coFilter:"http://feedjit.com/coFilter"},qStrCache:{},cookiesAreEnabled:null,scrToTxt:"",trafficFeedEnabled:false,flashVisible:true,flashHasLoaded:false,flashInserted:false,FNVCalled:false,flCallbacks:[],totFLTime:0,logRun:false,cssNodes:{},widgetsRun:{},clickTInst:false,flashElemId:false,vid:null,filterOn:null,readyBound:false,domIsReady:false,
onDomReadyFuncs:[],logDivInserted:false,logDivElem:false,logStartTime:(new Date).getTime(),logData:"",init:function(){this.bindReady();this.setupClickTrk();this.cookiesInit()},cookiesInit:function(){if(this.cookiesEnabled()){var a=this.readCookie("_fjvid1");if(a)this.vid=a;else{this.vid="new";this.isNewVisit=true}this.createCookie("_fjvid1",a,1800)}else this.vid="cookiesDisabled"},addOnDomReady:function(a){this.domIsReady?a():this.onDomReadyFuncs.push(a)},domReady:function(){if(!this.domIsReady){this.domIsReady=
true;for(var a=0;a<this.onDomReadyFuncs.length;a++)this.onDomReadyFuncs[a]()}},bindReady:function(){if(!this.readyBound){this.readyBound=true;if(document.addEventListener)document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,false);fjit.domReady()},false);else if(document.attachEvent){document.attachEvent("onreadystatechange",function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",arguments.callee);
fjit.domReady()}});document.documentElement.doScroll&&window==window.top&&function(){var a=this;if(!a.domIsReady){try{document.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}fjit.domReady()}}()}}},isFilterOn:function(){return this.filterOn?"1":"0"},flashDetect:new (function(){var a=this;a.installed=false;a.raw="";a.major=-1;a.minor=-1;a.revision=-1;a.revisionStr="";var b=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(e){return c(e)}},{name:"ShockwaveFlash.ShockwaveFlash.6",
version:function(e){var f="6,0,21";try{e.AllowScriptAccess="always";f=c(e)}catch(h){}return f}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(e){return c(e)}}];function c(e){var f=-1;try{f=e.GetVariable("$version")}catch(h){}return f}function d(e){var f=-1;try{f=new ActiveXObject(e)}catch(h){f={activeXError:true}}return f}function i(e){var f=e.split(",");return{raw:e,major:parseInt(f[0].split(" ")[1],10),minor:parseInt(f[1],10),revision:parseInt(f[2],10),revisionStr:f[2]}}function g(e){var f=
e.split(/ +/),h=f[2].split(/\./);f=f[3];return{raw:e,major:parseInt(h[0],10),minor:parseInt(h[1],10),revisionStr:f,revision:j(f)}}function j(e){return parseInt(e.replace(/[a-zA-Z]/g,""),10)||a.revision}a.FJ_FlashDetect=function(){if(navigator.plugins&&navigator.plugins.length>0){var e="application/x-shockwave-flash",f=navigator.mimeTypes;if(f&&f[e]&&f[e].enabledPlugin&&f[e].enabledPlugin.description){e=f[e].enabledPlugin.description;var h=g(e);a.raw=h.raw;a.major=h.major;a.minor=h.minor;a.revisionStr=
h.revisionStr;a.revision=h.revision;a.installed=true}}else if(navigator.appVersion.indexOf("Mac")==-1&&window.execScript){e=-1;for(f=0;f<b.length&&e==-1;f++){h=d(b[f].name);if(!h.activeXError){a.installed=true;e=b[f].version(h);if(e!=-1){h=i(e);a.raw=h.raw;a.major=h.major;a.minor=h.minor;a.revision=h.revision;a.revisionStr=h.revisionStr}}}}}()}),flashOn:function(){return this.flashDetect.installed&&this.flashDetect.major>=9?true:false},isIE:function(){return navigator.userAgent.indexOf("MSIE")!=-1},
getScrQ:function(a){for(var b=document.getElementsByTagName("script"),c=0;c<b.length;c++)if(b[c].src.indexOf(a)==0){a=b[c].src;return a.replace(/^[^\?]+\??/,"")}return""},getQVar:function(a,b){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0]==b)return d[1]}return""},get_cHost:function(){if(!(location&&location.protocol&&location.host&&/https?:/.test(location.protocol)))return"localhost";var a=location.host.replace(/^www\./i,"");a=a.replace(/:\d+$/,"");a=a.replace(/^\./,"");
a=a.replace(/\.$/,"");return(a=a.replace(/[^a-zA-Z0-9\.\-]+/g,""))?a:"localhost"},createCookie:function(a,b,c){if(c){var d=new Date;d.setTime(d.getTime()+c*1E3);c="; expires="+d.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/"},readCookie:function(a){if(document.cookie&&document.cookie.substr){a=a+"=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}}return null},
eraseCookie:function(a){this.createCookie(a,"",-1)},cookiesEnabled:function(){if(this.cookiesAreEnabled=="yes")return true;else if(this.cookiesAreEnabled=="no")return false;else{this.createCookie("_fjdet1","det",10);if(this.readCookie("_fjdet1")=="det"){this.cookiesAreEnabled="yes";return true}else{this.cookiesAreEnabled="no";return false}}},ignoreMe:function(a){if(this.cookiesEnabled()){if(this.readCookie("_fjIgnoreMe")=="1"){alert("Feedjit is already ignoring you.");a.innerHTML="Stop ignoring me";
var b=this}else{this.createCookie("_fjIgnoreMe","1",31536E3);alert("From now on you will be ignored by Feedjit on this website.\n\nIf you use a different browser or workstation, or if you clear\nyour browser's cookies you will need to tell Feedjit to ignore you again.");a.innerHTML="Stop ignoring me";b=this}a.onclick=function(){b.stopIgnoringMe(this);return false}}else alert("You do not have cookies enabled which means Feedjit is already ignoring you.")},stopIgnoringMe:function(a){if(this.cookiesEnabled())if(this.readCookie("_fjIgnoreMe")!=
"1")alert("Feedjit is not currently ignoring you.");else{this.eraseCookie("_fjIgnoreMe");alert("Feedjit has stopped ignoring you.");a.innerHTML="Ignore my browser";var b=this;a.onclick=function(){b.ignoreMe(this);return false}}else alert("You do not have cookies enabled which means Feedjit has no choice but to ignore you.")},injectCSS:function(a,b){var c=document.getElementsByTagName("head")[0],d=document.createElement("link");d.type="text/css";d.rel="stylesheet";d.href=a;d.media="screen";typeof this.cssNodes[b]!=
"undefined"&&this.cssNodes[b]&&this.cssNodes[b].parentNode&&this.cssNodes[b].parentNode.removeChild(this.cssNodes[b]);c.appendChild(d);this.cssNodes[b]=d},setNewVID:function(a){this.vid=a;this.createCookie("_fjvid1",a,1800)},getWQVar:function(a,b){this.qStrCache[a]||(this.qStrCache[a]=this.getScrQ(this.wUrlMap[a]));return this.getQVar(this.qStrCache[a],b)},makeWParams:function(a,b,c){var d=this.logRun?1:0;this.logRun=true;var i,g;if(screen&&screen.width&&screen.height){i=screen.width;g=screen.height}else g=
i=0;var j="0",e=this.flGet("gid");if(e)j=e;a="w="+b+"&ign="+(this.readCookie("_fjIgnoreMe")=="1"?"1":"0")+"&wn="+a+"&cen="+(this.cookiesEnabled()?"1":"0")+"&nv="+(this.isNewVisit?"1":"0")+"&fl="+this.isFilterOn()+"&vid="+this.vid+"&rn="+(typeof this.widgetsRun[c]=="undefined"?"0":"1")+"&lg="+(d?"0":"1")+"&u="+encodeURIComponent(location.href)+"&r="+encodeURIComponent(document.referrer)+"&t="+encodeURIComponent(document.title)+"&sw="+i+"&sh="+g+"&wh="+this.getWQVar(b,"wh")+"&pid="+this.getWQVar(b,
"pid")+"&wid="+this.getWQVar(b,"wid")+"&hl="+this.getWQVar(b,"hl")+"&hlnks="+this.getWQVar(b,"hlnks")+"&gid="+j+"&flt="+this.totFLTime+"&fv="+(this.flashVisible?"1":"0")+"&tfen="+(this.trafficFeedEnabled?"1":"0")+"&fjv=2&rand="+Math.floor(Math.random()*999999999);this.widgetsRun[c]=1;return a},pause:function(a){var b=new Date,c=null;do c=new Date;while(c-b<a)},eDec:function(a){var b=document.createElement("textarea");b.innerHTML=a.replace(/</g,"&lt;").replace(/>/g,"&gt;");return b.value},shortenPre:function(a,
b){if(a.length<=b)return a;b-=3;a=a.substr(a.length-b,b);return a="..."+a.replace(/^[^\s\r\n\t]+[\s\r\n\t]+/,"")},shortenPost:function(a,b){if(a.length<=b)return a;b-=3;a=a.substr(0,b);return a=a.replace(/[\s\r\n\t]+[^\s\r\n\t]+$/,"")+"..."},handleAClick:function(a,b){b=b||window.event;b=a.href;for(var c=a.innerHTML?this.eDec(a.innerHTML.replace(/<[^>]+>/g,"")):"",d="",i="",g=a;(g=g.previousSibling)&&d.length<255;)if(g.nodeType==3)d=this.eDec(g.nodeValue)+d;else if(g.nodeType==1&&g.firstChild&&g.firstChild===
g.lastChild&&g.firstChild.nodeType==3)d=this.eDec(g.firstChild.nodeValue)+d;else break;for(a=a;(a=a.nextSibling)&&i.length<255;)if(a.nodeType==3)i+=this.eDec(a.nodeValue);else if(a.nodeType==1&&a.firstChild&&a.firstChild===a.lastChild&&a.firstChild.nodeType==3)i+=this.eDec(a.firstChild.nodeValue);else break;c=c.replace(/[\s\r\n\t]+/g," ");d=d.replace(/[\s\r\n\t]+/g," ");i=i.replace(/[\s\r\n\t]+/g," ");c=this.shortenPost(c,125);d=this.shortenPre(d,125);i=this.shortenPost(i,125);a="0";if(g=this.flGet("gid"))a=
g;g=document.createElement("IMG");g.width="1";g.height="1";g.alt="blah";g.src="http://feedjit.com/click/?&h="+encodeURIComponent(b)+"&u="+encodeURIComponent(location.href)+"&cen="+(this.cookiesEnabled()?"1":"0")+"&vid="+this.vid+"&ign="+(this.readCookie("_fjIgnoreMe")=="1"?"1":"0")+"&fl="+this.isFilterOn()+"&lnt="+encodeURIComponent(c)+"&prt="+encodeURIComponent(d)+"&pot="+encodeURIComponent(i)+"&gid="+a+"&tfen="+(this.trafficFeedEnabled?"1":"0")+"&fjv=2&t="+encodeURIComponent(document.title.replace(/[\s\r\n\t]+/g,
" "))+"&rand="+Math.floor(Math.random()*999999999);document.body.appendChild(g);b=document.createElement("IMG");b.width="1";b.height="1";b.alt="";b.src="http://feedjit.com/images/transparent.gif?r="+Math.floor(Math.random()*999999999);document.body.appendChild(b);fjit.pause(500);return true},installATrack:function(a){if(typeof a.onclick!="function")a.onclick=function(b){return fjit.handleAClick(this,b)}},processLinks:function(){for(var a=document.body.getElementsByTagName("A"),b=0;b<a.length;b++)/^(http:\/\/|\/)/.test(a[b].href)&&
this.installATrack(a[b])},getStyle:function(a,b){var c="";if(document.defaultView&&document.defaultView.getComputedStyle)c=document.defaultView.getComputedStyle(a,"").getPropertyValue(b);else if(a.currentStyle){b=b.replace(/\-(\w)/g,function(d,i){return i.toUpperCase()});c=a.currentStyle[b]}return c},e:function(a){return document.getElementById(a)},setupClickTrk:function(){var a=this;if(!this.clickTInst){this.clickTInst=true;var b=window.onload,c=function(){a.processLinks()};window.onload=typeof window.onload!=
"function"?c:function(){a.processLinks();b()}}},scrollTo:function(a){a=this.e(a);for(var b=0,c=0;a!=null;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}window.scrollTo(b,c)},logAddScrollTo:function(a,b){this.scrToTxt+='&nbsp;&nbsp;<a href="#" onclick="fjit.scrollTo(\''+a+'\'); return false;" style="text-decoration: underline;">'+b+"</a>";if(a=this.e("FJ_S_TO"))a.innerHTML=this.scrToTxt},log:function(a,b){if(b)b+=":&nbsp;";else b="";this.logData=b+((new Date).getTime()-this.logStartTime)+": "+a+
"<br />"+this.logData;if(this.logDivInserted){a=this.logDivElem.firstChild.nextSibling;a.innerHTML=this.logData}},appendLogDiv:function(){if(!this.logDivInserted){this.logDivInserted=true;var a=document.createElement("DIV");a=document.createElement("DIV");a.style.position="fixed";a.style.zIndex=99999999;a.style.textAlign="left";a.style.left="0px";a.style.bottom="0px";a.style.border="2px solid #F00";a.style.width="600px";a.style.height="200px";a.style.overflow="scroll";a.style.fontSize="10px";a.style.fontFamily=
"Arial";a.style.color="#000";a.style.backgroundColor="#FFF";a.innerHTML='<div><img src="http://feedjit.com/images/logos/feedjit.gif" width="64" height="14" alt="" align="absmiddle" />&nbsp;&nbsp;<span id="FJ_S_TO"></span></div><div id="divLOG"></div>';var b=a.firstChild.nextSibling;b.innerHTML=this.logData;this.logDivElem=a;document.body.appendChild(this.logDivElem);this.e("FJ_S_TO").innerHTML=this.scrToTxt}},isThisVisible:function(a){a=fjit.e(a);try{for(;a=a.parentNode;){if(a.tagName.toUpperCase()==
"BODY")break;var b=fjit.getStyle(a,"display");if(b=="none")return false}}catch(c){}return true},setFlashElemId:function(a){this.flashElemId=a},flGet:function(a){if(this.flashElemId){var b=false;try{b=this.e(this.flashElemId).fjfGet(a)}catch(c){}if(b)return b}return false},flSet:function(a,b){if(this.flashElemId)try{this.e(this.flashElemId).fjfSet(a,b)}catch(c){}},addOnFlash:function(a,b){if(this.flashHasLoaded){this.log("in addOnFlash() flashHasLoaded is true, so executing callback immediately",b);
a()}else{this.log("in addOnFlash() flash has not loaded yet, so queueing callback",b);this.flCallbacks.push(a)}},doWrite:function(a,b,c){this.log("Starting "+a+" widget creation",a);if(fjit.flashOn())if(this.flashHasLoaded){this.log("Flash already loaded at start of doWrite(). Doing basic doc.write and executing cb() immediately",a);document.write(b);c()}else if(this.flashInserted){this.log("Flash is already inserted. Writing basic div and setting up callback and returning.",a);document.write(b);
this.addOnFlash(c,a)}else{this.setFlashElemId("FJ_FL_Obj");b='<div id="FJ_FL_Cont" style="width: 1px; height: 1px; border-width: 0; padding: 0; margin: 0;"><object id="FJ_FL_Obj" type="application/x-shockwave-flash" data="http://feedjit.com/images/flash/fj.swf" width="1" height="1"><param name="AllowScriptAccess" value="always" /><param name="movie" value="http://feedjit.com/images/flash/fj.swf" /></object></div>'+b;document.write(b);this.flashInserted=true;this.log("Adding callback for "+
a);this.addOnFlash(c,a);this.flStartTime=(new Date).getTime();if(this.isThisVisible("FJ_FL_Cont")){this.log("Widget is visible",a);var d=this;setTimeout(function(){d.flashLoaded(true)},1E4)}else{this.flashVisible=false;this.log("Widget is NOT visible");if(this.isIE())if(this.domIsReady){this.log("Browser is IE and DOM is ready - inserting visible flash",a);this.flashNotVisible(a)}else{this.log("Browser is IE - setting up onDomReady to insert visible flash",a);d=this;this.addOnDomReady(function(){d.flashNotVisible(a)})}else{this.log("Inserting visible flash into DOM",
a);this.flashNotVisible(a)}}}else{this.log("Flash not enabled. Calling doc.write and running callback immediatelly.",a);document.write(b);c()}},flashNotVisible:function(a){if(this.FNVCalled)this.log("FNV already called",a);else{this.FNVCalled=true;var b=document.createElement("DIV");b.style.width="1px";b.style.height="1px";b.style.borderWidth="0px";document.body.appendChild(b);this.setFlashElemId("FJ_FL_Obj2");b.innerHTML='<div style="width: 1px; height: 1px; border: 0; padding: 0;"><object id="FJ_FL_Obj2" type="application/x-shockwave-flash" data="http://feedjit.com/images/flash/fj2.swf" width="1" height="1"><param name="AllowScriptAccess" value="always" /><param name="movie" value="http://feedjit.com/images/flash/fj2.swf" /></object></div>';
this.log("Added new flash object to DOM",a);var c=this;setTimeout(function(){c.flashLoaded(true)},1E4)}},flashLoaded:function(a){if(!this.flashHasLoaded){this.flashHasLoaded=true;if(a){this.log("WARNING: fjit.flashLoaded() called through timeout - Flash did not load.");this.totFLTime="0"}else{this.log("Flash loaded succesfully!");if(this.flGet("fjdebug")=="1")if(this.isIE()){var b=this;this.addOnDomReady(function(){b.appendLogDiv()})}else this.appendLogDiv();this.totFLTime=(new Date).getTime()-this.flStartTime}if(this.flCallbacks.length>
0)for(a=0;a<this.flCallbacks.length;a++){this.log("Executing callback #"+a);this.flCallbacks[a]()}}}};fjit.init()}
var fjltf={flStartTime:0,init:function(){this.setup()},setup:function(){fjit.trafficFeedEnabled=true;fjit.logAddScrollTo("FJ_TF_Cont","Traffic Feed");var a=fjit.getScrQ("http://feedjit.com/serve");fjit.filterOn=fjit.getQVar(a,"fl")==1?true:false;fjit.injectCSS("http://feedjit.com/style/26/serve/?"+a,"FJ_TL_CSS");var b=this;fjit.doWrite("TFeed",'<div id="FJ_TF_Cont"></div>',function(){b.fl()})},fl:function(){var a=fjit.makeWParams("1","trafficList","FJ_TL_RUN"),b=document.createElement("SCRIPT");b.charset=
"utf-8";b.type="text/javascript";b.src="http://feedjit.com/router/?"+a;document.getElementsByTagName("head")[0].appendChild(b)},proc:function(a){fjit.e("FJ_TF_Cont").innerHTML=a}};function FJ_FLDone(a){fjltf.flashDone(a)}fjltf.init();
